services:
  - type: web
    name: crypto-data-analyzer
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --timeout 120
    envVars:
      - key: SECRET_KEY
        generateValue: true
